### ISSUE TITLE
To implement AirInterfacePowerSaver version 0.0.5

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/AirInterfacePowerSaver#93]
To completely implement the version 0.0.5 changes , the following tasks and their subtasks needs to be completed.
All the tasks needs to be implemented , tested , reviewed and merged to the develop branch.

### Initial setup and integration of ApplicationPattern :
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/79
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/80 
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/81
- [x] Software upgrade module https://github.com/openBackhaul/AirInterfacePowerSaver/issues/87

### Individual Services :
Before start implementating the individual services , the following functionalities need to be included for code reusuablity , 
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/82
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/83 

Further the following services shall be implemented , 
#### Link related switching operation 
- [x] To switchOFF the parallel links https://github.com/openBackhaul/AirInterfacePowerSaver/issues/91
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/92
- [x] To reactivate the switchedOFF links https://github.com/openBackhaul/AirInterfacePowerSaver/issues/89
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/88

#### Link analysis 
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/90

#### PowerSavingStatus
The power saving status shall be stored in the PowerSavingStatus table in the ElasticSearch. The following services needs to be implemented to store , retrieve and modify the power saving status, 
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/84
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/85
- [x] https://github.com/openBackhaul/AirInterfacePowerSaver/issues/86
